import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

// Done with the imports man

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40  dark:bg-gray-900">
        <section>
          <nav className="py-8 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-gray-300">Bro Sans</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  className="cursor-pointer text-2xl dark:text-gray-100"
                  onClick={() => {
                    setDarkMode(!darkMode);
                  }}
                />
              </li>
              <li>
                <a
                  href="#"
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-full ml-8"
                >
                  MY RESUME
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 dark:text-teal-300 font-medium md:text-6xl">
              Muhammad Umar
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-gray-300">
              MERN stack developer and Data Science Enthusiast
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 md:text-m max-w-xl mx-auto dark:text-gray-300">
              A boi who likes to make Awesome and cool projects in the Mern
              stack and want to become a ML expert in the future. Also love dota
              2.
            </p>
          </div>
          <div className="text-5xl flex justify-center py-3 gap-6 text-gray-600 ">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-800 rounded-full w-60 h-60 md:w-96 md:h-96 mt-5 overflow-hidden">
            <Image src={deved} fill style={{ objectFit: "cover" }} />
          </div>
        </section>
        {/* This is the second section here */}

        <section>
          <div>
            <h3 className="text-2xl py-1 dark:text-gray-200">Who Am I?</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              I am COMSATS university graduate in Computer Science and also a MERN stack developer. I also have good proficiency in Linux and Github
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              In the future I want to become a data scientist and to make my own machine learning models.
            </p>
          </div>
          <div className="lg:flex gap-6 my-20">
            <div className="text-center shadow-lg p-10 rounded-xl shadow-gray-300 dark:shadow-gray-800 dark:bg-gray-300">
              {/* Text center classname in the div tag wsan't working with the image tag. Why??? */}
              <Image
                src={design}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg pt-8 pb-2 font-medium">Beautiful Code</h3>
              <p className="py-2">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio id
                corporis libero eaque sequi nemo?
              </p>
              <h4 className="py-4 text-teal-600">Environments I use</h4>
              <p className="text-gray-800 py-1">IDLE</p>
              <p className="text-gray-800 py-1">JDK</p>
              <p className="text-gray-800 py-1">VSCODE</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl shadow-gray-300 dark:shadow-gray-800 dark:bg-gray-300 ">
              {/* Text center classname in the div tag wsan't working with the image tag. Why??? */}
              <Image src={code} width={100} height={100} className="mx-auto" />

              <h3 className="text-lg pt-8 pb-2 font-medium">Beautiful Code</h3>
              <p className="py-2">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio id
                corporis libero eaque sequi nemo?
              </p>
              <h4 className="py-4 text-teal-600">Environments I use</h4>
              <p className="text-gray-800 py-1">IDLE</p>
              <p className="text-gray-800 py-1">JDK</p>
              <p className="text-gray-800 py-1">VSCODE</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl shadow-gray-300 dark:shadow-gray-800 dark:bg-gray-300">
              {/* Text center classname in the div tag wsan't working with the image tag. Why??? */}
              <Image
                src={consulting}
                width={100}
                height={100}
                className="mx-auto"
              />

              <h3 className="text-lg pt-8 pb-2 font-medium">Beautiful Code</h3>
              <p className="py-2">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio id
                corporis libero eaque sequi nemo?
              </p>
              <h4 className="py-4 text-teal-600">Environments I use</h4>
              <p className="text-gray-800 py-1">IDLE</p>
              <p className="text-gray-800 py-1">JDK</p>
              <p className="text-gray-800 py-1">VSCODE</p>
            </div>
          </div>
        </section>

        {/* Final section is gonna be here */}

        <section>
          <h3 className="text-3xl py-1 text-gray-800 dark:text-gray-200">Portfolio</h3>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam
            odio adipisci at assumenda debitis natus, molestiae nesciunt tenetur
            inventore temporibus?
          </p>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt odit
            reiciendis delectus dolor veritatis tempora debitis neque dicta,
            totam, et quam!
          </p>
          <div className="flex flex-col gap-10 py-9 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                style={{ layout: "responsive" }}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                style={{ layout: "responsive" }}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                style={{ layout: "responsive" }}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                style={{ layout: "responsive" }}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                style={{ layout: "responsive" }}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                style={{ layout: "responsive" }}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
